openapi: 3.0.3
info:
  title: Roman Numerals API
  version: 1.0.0
  description: This API does the conversion to Roman Numerals

servers:
  - url: http://localhost:8080/api/v1
    description: Local development

tags:
  - name: Convert
    description: 'API to convert numbers'

paths:
  /convert/integers:
    summary: Convert range of integers to Roman Numerals
    description: API to convert range of integers to Roman Numerals
    post:
      summary: Convert integer range to roman numerals
      description: API for conversion
      operationId: convertIntegerToRoman
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntegerRangeRequest'
        required: true
      tags:
        - Convert
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfRomanNumeralStrings'
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageResponse'
          description: Bad request

components:
  schemas:
    ArrayOfRomanNumeralStrings:
      type: array
      items:
        type: string
      example:
        - "I"
        - "II"
        - "III"

    IntegerRangeRequest:
      title: Root Type for IntegerRangeRequest
      description: Defines the request object
      required:
        - to
        - from
      type: object
      properties:
        from:
          format: int32
          maximum: 3999
          minimum: 1
          type: integer
          example: 1
        to:
          format: int32
          maximum: 3999
          minimum: 1
          type: integer
          example: 3

    ErrorMessageResponse:
      title: Root Type for ErrorMessageResponse
      description: Defines the error response object
      type: object
      properties:
        errorCount:
          format: int32
          type: integer
          example: 1
        errors:
          type: array
          items:
            type: string
          example:
            - "descriptive error message"
