name: Application Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  build-job:
    name: Build and test the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          architecture: x64
      - name: Build project with Maven
        run: mvn package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    name: Publish the package
    needs: build-job
    steps:
      - name: "TODO: Deploy package"
        run: 'echo "Run deployment"'
